
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const OUTPUT_PATH = path.join(__dirname, '../src/data/history_auto.js');

try {
    // 1. Get detailed git logs (Hash | Date | Message)
    const gitLog = execSync('git log -n 20 --pretty=format:"%h|%ad|%s" --date=short').toString();

    // 2. Formatting Rules
    const TYPE_MAP = {
        'feat': '✨ 기능 구현',
        'fix': '🔧 수정',
        'docs': '📝 문서',
        'style': '🎨 스타일',
        'refactor': '♻️ 구조 개선',
        'perf': '🚀 성능 최적화',
        'test': '✅ 테스트',
        'chore': '⚙️ 시스템',
        'revert': '⏪ 롤백'
    };

    const IGNORE_PATTERNS = [
        'merge branch',
        'wip',
        'typo'
    ];

    const formatMessage = (msg) => {
        // Common Dictionary for automatic translation
        const DICT = {
            'remove': '제거', 'delete': '삭제', 'fix': '수정', 'resolve': '해결',
            'implement': '구현', 'add': '추가', 'update': '업데이트', 'refine': '다듬기',
            'refactor': '구조 개선', 'chore': '관리', 'feat': '기능',
            'audio': '오디오', 'system': '시스템', 'sound': '사운드', 'hud': 'UI',
            'naming': '이름', 'philosophy': '기획 철학', 'autoselection': '자동 선택',
            'logic': '로직', 'safety': '안전장치', 'crash': '충돌', 'optimization': '최적화',
            'performance': '성능', 'deploy': '배포', 'artifacts': '산출물',
            'merge': '병합', 'branch': '브랜치', 'sensitive': '보안', 'files': '파일',
            'scene': '씬', 'transition': '전환', 'immersion': '몰입감', 'solar': '태양계',
            'constellation': '별자리', 'component': '컴포넌트', 'click': '클릭',
            'autoplay': '자동재생', 'mute': '음소거', 'log': '로그', 'visualization': '시각화'
        };

        let processedMsg = msg;

        // 1. Prefix Removal ([feat], feat: etc)
        const match = msg.match(/^\[?(\w+)\]?[:\s]\s*(.*)/i);
        let type = 'update';
        let content = msg;

        if (match) {
            type = match[1].toLowerCase();
            content = match[2];
        }

        // 2. Content Translation (Simple Replace)
        Object.keys(DICT).forEach(key => {
            const regex = new RegExp(key, 'gi'); // Case insensitive
            content = content.replace(regex, DICT[key]);
        });

        // 3. Type Formatting
        if (TYPE_MAP[type]) {
            return `${TYPE_MAP[type]}: ${content}`;
        }

        // Fallback for unknown types
        return `🛠️ 업데이트: ${content}`;
    };

    // 3. Process Commits
    const changes = gitLog.split('\n')
        .filter(Boolean)
        .map(line => {
            const [hash, date, message] = line.split('|');
            return { hash, date, message };
        })
        .filter(commit => {
            // Filter redundant chore commits if needed, or keeping them minimal
            const lowerMsg = commit.message.toLowerCase();
            if (IGNORE_PATTERNS.some(p => lowerMsg.includes(p))) return false;
            // Only show significant updates
            return true;
        })
        .map(commit => formatMessage(commit.message))
        .slice(0, 10); // Limit to 10 meaningful items

    const autoEntry = {
        version: "Recent Dev Stream",
        date: new Date().toISOString().split('T')[0],
        title: "DEVELOPER LOG (LIVE)",
        changes: changes.length > 0 ? changes : ["No recent notable changes."]
    };

    const content = `// This file is auto-generated by scripts/generate-history.js
export const autoHistory = [
    ${JSON.stringify(autoEntry, null, 4)}
];
`;

    fs.writeFileSync(OUTPUT_PATH, content);
    console.log(`[Success] Generated history_auto.js with ${changes.length} items.`);

} catch (error) {
    console.warn("[Warning] Git history generation failed. Using empty fallback.");
    const fallbackContent = `export const autoHistory = [];`;
    fs.writeFileSync(OUTPUT_PATH, fallbackContent);
}
